### ISSUE TITLE
Standalone BigInt

### ISSUE THREAD

**Issue by somebody1234** [vibornoff/asmcrypto.js#102]
Is it possible to create a standalone package with just the bigint parts?

**Comment by vibornoff** [comment]
One does not simply build bigint-only asmCrypto :)

Take a look into [Gruntfile.js](https://github.com/vibornoff/asmcrypto.js/blob/master/Gruntfile.js):
* `bn` component depends on `rng`
* `rng` for safe work in legacy browsers depends on `pbkdf2-hmac-sha256`

**Comment by somebody1234** [comment]
So then it's possible to build with only those three?

**Comment by vibornoff** [comment]
Yep, `grunt --with=utils,bn` proceeds
