### ISSUE TITLE
native crypto.getRandomValues gets overriden even when implemented by the browser

### ISSUE THREAD

**Issue by johndoughnut** [vibornoff/asmcrypto.js#108]
Even when the browser (e.g. chrome) implements getRandomValues (using system-secure and very fast PRNG), asmCrypto overrides it. 
I think it should be optional or at least configurable.

**Comment by palant** [comment]
As a work-around, one can run `delete crypto.getRandomValues` after loading asmCrypto. Still, this should not be necessary.
