### ISSUE TITLE
production ready and tutorials on common use-cases

### ISSUE THREAD

**Issue by siddo420** [vibornoff/asmcrypto.js#110]
Is it production-ready now?

what browsers does it support?

Are there any tutorials written for simple use cases such as encrypting and decrypting strings between client and server etc?

**Comment by vibornoff** [comment]
Yep, it's production ready. MEGA uses it for file encryption.

It supports IE10+, FF22+, Safari 5.1+, Chrome (I don't remember the earliest version started supporting it).

Unfortunately there are no tutorials, but you can study test scripts under `test/`
