### ISSUE TITLE
PBDKF2 on iPad4 (Air) very slow

### ISSUE THREAD

**Issue by jochenonline** [vibornoff/asmcrypto.js#67]
When calling key derivation like this

    asmCrypto.PBKDF2_HMAC_SHA256.base64(password, salt, it, 16);

with `it: 100000`, which lasts on a "normal" pc alway less than 2 seconds, my new iPad needs 18 (eighteen!) seconds. Is this the expected behaviour or is there something wrong?

**Comment by vibornoff** [comment]
Expected. Safari performance is terrible.

**Comment by alippai** [comment]
Maybe an upgrade to iOS8 helps.

**Comment by jochenonline** [comment]
Yes, indeed. I had iOS7. On iOS 8.1.2 ==> 3 sec :-)
