### ISSUE TITLE
IE9 : Unable to get value of property 'encrypt'

### ISSUE THREAD

**Issue by mrbinr** [vibornoff/asmcrypto.js#72]
Hi,
I'm using asmcryto.js but on IE9 i have message : 

TypeError: Unable to get value of the property 'encrypt': object is null or undefined

The code which i'm using : 
asmCrypto.bytes_to_base64(asmCrypto.AES_CBC.encrypt(str, decodeKey(), true, decodeKey()));

decodeKey() is a internal function , and str string to be crypted.

Thanks for your job and your help

Best Regards
Pascall

**Comment by vibornoff** [comment]
I'm sorry, but IE9 lacks of support of [typed arrays](http://caniuse.com/#feat=typedarrays), the core feature asmcrypto relies on.
