### ISSUE TITLE
Different values depending on input type

### ISSUE THREAD

**Issue by jvsteiner** [vibornoff/asmcrypto.js#74]
I am getting different hash values:

```javascript
fr = new FileReader();
fr.readAsArrayBuffer(file);

asmCrypto.SHA256.hex(fr.results); //gets one answer from original ArrayBuffer
asmCrypto.SHA256.hex(new Uint8Array(fr.result)); // gets same answer when read into Uint8Array
asmCrypto.SHA256.hex(new ArrayBuffer(new Uint8Array(fr.result))); // gets different answer if I convert back into ArrayBuffer
```

shouldn't this work?

**Comment by vibornoff** [comment]
Nope it shouldn't. Take a look to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

The result of `new ArrayBuffer(new Uint8Array(fr.result))` is the same as for `new ArrayBuffer(NaN)`.
