### ISSUE TITLE
disappearance of Git tags

### ISSUE THREAD

**Issue by pohutukawa** [vibornoff/asmcrypto.js#76]
We've just had to recover from a whole bunch of projects misbehaving due to the disappearance of a tagged asmcrypto.js release `v0.0.7`. Why was that tag removed? Projects often require tagging of working releases, e. g. in a `package.json` file, and *deleting* a release tag just breaks this mechanism severely.

**Comment by vibornoff** [comment]
`v0.0.7` was removed after issue #70 has been fixed.

Unfortunately git doesn't provide a way to blacklist some releases. So removing a tag seems a less evil to me compared to either letting the broken release to be available for everyone or retagging different commit with the same tag name.
