### ISSUE TITLE
Need RSA-SHA1 signature

### ISSUE THREAD

**Issue by tombrown52** [vibornoff/asmcrypto.js#78]
I need to sign some data using RSA-SHA1 but other pure JS libraries are too slow. Is there a way to do it with this asmcrypto?

**Comment by vibornoff** [comment]
Sure, you can do it with `asmCrypto.RSA_PSS_SHA1.sign( data, key )` and verify the signature with `asmCrypto.RSA_PSS_SHA1.verify( signature, data, key )`.

For more useful examples take a look to the test suite: https://github.com/vibornoff/asmcrypto.js/blob/master/test/rsa.js#L93

**Comment by tombrown52** [comment]
That is excellent! What is the easiest way to load a private key from PEM/PKCS#1 format?

**Comment by vibornoff** [comment]
Unfortunately asmCrypto doesn't provide support for crypto formats. It's out of the scope of this project. 
You can try to parse your PEM key with https://github.com/GlobalSign/ASN1.js and then proceed with the `[ m, e ]` tuple as a public key or with `[ m, e, d, p, q, dp, dq, qi ]` as a private key.
