### ISSUE TITLE
CBC - how to specify padding

### ISSUE THREAD

**Issue by b354c502** [vibornoff/asmcrypto.js#87]
Your docs mention:
"Optional padding and iv may be passed to override default settings (PKCS#7 padding is on and iv is zero-vector)."

A zero-iv is a dangerous default. However, if I specify an IV, I also need to specify the padding. How is this done? Is there a constant for PKCS#7 padding which I can pass when calling the method?  Ie, asmCrypto.AES_CBC.encrypt(clearText, key, ???, iv);

**Comment by vibornoff** [comment]
_PKCS#7_ is the only supported padding scheme. Just pass `true` to indicate the padding is turned on:
```js
asmCrypto.AES_CBC.encrypt( clearText, key, true, iv );
```

**Comment by b354c502** [comment]
Thanks!
