### ISSUE TITLE
[Feature Request] Split to modules

### ISSUE THREAD

**Issue by btd** [vibornoff/asmcrypto.js#88]
Hello.

It will be very nice and convenient (for file size) if it will be possible to split this library to modules like aes-256-cbc or just aes-cbc.
I know it can be hard to maintain but still it will be very convenient.

Thanks.

**Comment by alpdeniz** [comment]
It is already split to modules. Have a look at the Gruntfile and re-compile again with your selected modules.

**Comment by btd** [comment]
If i can compile everything why i need modules at all (aka for what bower/npm/jspm was created?)? I mean exactly e.g: publish separate modules in npm or have in repo compiled modules, that i can just `require` exact file-module, that my app uses.

**Comment by vibornoff** [comment]
@alpdeniz rigth, it already split into modules. Take a look into _Gruntfile.js_ and into the _src/_ folder. You of course can use these files directly.

Regarding the minified _asmcrypto.js_ -- in your production environment you must not ever use any scripts hosted at sites out of your exclusive control. It's basic security requirement. So as you have to host your own copy of _asmcrypto.js_ why not to build it into 1 file all the stuff you need?

**Comment by alpdeniz** [comment]
I had suspicion so I had a look to see if asmjs support is available on nodejs and if it makes sense to release a npm package to use with require. However, asmjs won't be supported by node until it becomes a standard in V8, except jxcore - [related post](http://oguzbastemur.blogspot.com.uy/2015/02/now-asmjs-is-available-for-nodejs.html)

Though, it would a good idea if it was supported by V8.

**Comment by vibornoff** [comment]
There is already a handful of crypto stuff in npm packages and built-in OpenSSL support out of the box.

![image](https://cloud.githubusercontent.com/assets/506386/10113222/ed2e44e2-63ea-11e5-8534-9049c5bbc37a.png)

**Comment by btd** [comment]
@vibornoff just FYI, it is pretty usual practice to write isomorphic modules, that uses the same code in node.js and browser. So your picture is fully irrelevant. Your library - your choices.
