### ISSUE TITLE
Use the original uglifyjs

### ISSUE THREAD

**Issue by alippai** [vibornoff/asmcrypto.js#89]
I think it's possible now to use the original repository instead of the fork.
https://github.com/mishoo/UglifyJS2/commit/593677d2ff04f61a2230c18722ec89b820ee0307

**Comment by vibornoff** [comment]
Will review the patch shortly.
There was a bug in FF asm.js implementation I've worked around and it seems unhandled to me after brief look to mishoo/UglifyJS2@593677d.

**Comment by alippai** [comment]
Well, if the FF issue is fixed in the ESR version, then we are good.

**Comment by vibornoff** [comment]
Just checked the latest version of UglifyJS
```sh
$ node_modules/.bin/uglifyjs -V
uglify-js 2.5.0
```

With the code snippet:
```js
!function X () {
    function A () {
        "use asm";

        function A () {
            return 42;
        }

        return {
            A: A
        };
    }
    window.asm = A;
}();

```
output is:
```js
!function(){function n(){"use asm";function n(){return 42}return{A:n}}window.asm=n}();
```
and causes Firefox/41 to throw
```
TypeError: asm.js type error: duplicate name 'n' not allowed
```

Well @rvanvelzen, good try...
