### ISSUE TITLE
RSA key pair and Web Cryptography API compatibility

### ISSUE THREAD

**Issue by ssmtlbn** [vibornoff/asmcrypto.js#90]
I have two questions about RSA key generation.

* The function `RSA.generateKey( bitlen, pubexp )`  generates a private RSA key. But how do I get the public key then?
* The return value of `RSA.generateKey( bitlen, pubexp )` is an Array of 8 Uint8Array`s (maybe because of the chinese remainder algorithm?). Is there a way to transform these Arrays to a [CryptoKey](https://developer.mozilla.org/en-US/docs/Web/API/CryptoKey) ([importKey](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/importKey)) to make it compatible to the Web Cryptography API (and vice versa)?

**Comment by vibornoff** [comment]
The key returned from `RSA.generateKey(...)` is a tuple of bigints `[ n, e, d, p, q, dp, dq, qi ]`.

Public key components are the first two elements `[ n, e ]`.

You can transform it into the *"jwk"* format compatible with WebCrypto `importKey` with the next pseudo-code snippet:
```js
var jwk = {
    kty: "RSA",
    alg: "RS256",                      // Your desired JWA algorithm
    ext: true,                              // Is key extractable or not
    key_ops: [ "sign", "verify" ], // Array of supposed key usages

    // Public key components
    e: "AQAB",                          // The "e" component, public exponent, spec restricts is to the only value, 65537
    n: base64url_encode( key[0] ),

    // Private key components
    d: base64url_encode( key[2] ),
    p: base64url_encode( key[3] ),
    q: base64url_encode( key[4] ),
    dp: base64url_encode( key[5] ),
    dq: base64url_encode( key[6] ),
    qi: base64url_encode( key[7] ),
};
```

BTW, do you really need to generate RSA key with asmcrypto once you suppose it to be used with WebCrypto?

**Comment by ssmtlbn** [comment]
Thank you for your quick response and help ;) It seems to work...see [this fiddle](http://jsfiddle.net/7uy91fud/2/).
As you can see, I used the function `asmCrypto.bytes_to_base64()` to encode the bytes to Base64 format. As I saw in the source code, `bytes_to_base64` uses `btoa()` which is not url safe. But it seems not be a problem for the quick fiddle test (maybe later?!).

I want to use asmcrypto as fallback if WebCrypto is not available. So it could be possible that a user generates a key and encrypts data with WebCrypto and later comes back with another browser which doesn`t WebCrypto (IE 10, Firefox in WebWorker, ..). Then asmcrypto should be used to decrypt the data.
So I don´t really want to generate the RSA key with asmcrypto and use it right after with WebCrypt ;)
