### ISSUE TITLE
RSA KeyGeneration slower than OpenPGP

### ISSUE THREAD

**Issue by jochenonline** [vibornoff/asmcrypto.js#93]
When comparing RSA-Key-Generation between asmcrypto and [OpenPGP](https://github.com/openpgpjs/openpgpjs) on the same machine and in same browser and with the same bit-length (4096) OpenPGP is almost twice as fast as asmcrypto (average time 13,3 sec vs 20,2 sec). Do you see any obvious reason for that or am I comparing apples with oranges?

**Comment by vibornoff** [comment]
Is your result statistically significant? I mean did you calculate [Standard deviation](https://en.wikipedia.org/wiki/Standard_deviation) along with the average time?

**Comment by jochenonline** [comment]
Standard daviation
* asmcrypto: 9,7
* OpenPGP: 2,2

So the times of OpenPGP are also much more stable. Theses are the times we have measured:

asmcrypto:
* 35,7
* 25,7
* 9,6
* 21
* 11,7
* 5,1
* 32,8
* 16,2
* 19,5
* 29,3

OpenPGP:
* 12,7
* 11,6
* 10,8
* 13,9
* 11,2
* 15,2
* 15,9
* 17,1
* 10,4
* 13,8

**Comment by vibornoff** [comment]
Having a brief look to the [opengpg.js source](https://github.com/openpgpjs/openpgpjs/blob/master/src/crypto/public_key/rsa.js#L143) I suppose it's because your browser supports WebCrypto API :)
