### ISSUE TITLE
Missing asmcrpyto.js in bower package on 0.0.11 version

### ISSUE THREAD

**Issue by offlinehacker** [vibornoff/asmcrypto.js#97]
asmcrypto.js file is missing in 0.0.11 release from bower

**Comment by cvlmtg** [comment]
+1

and for some reason, 0.0.10 is no longer available, so we can no longer build our app with the latest tested and functioning version...

**Comment by vibornoff** [comment]
Sorry guys, 0.0.10 is pushed back

**Comment by cvlmtg** [comment]
thanks!

**Comment by vibornoff** [comment]
Regarding _v0.0.11_, I retagged it to a different commit, my fault. I have to delete _v0.0.11_ and increment verson number to _v0.0.12_.

**Comment by offlinehacker** [comment]
Thanks!
