### ISSUE TITLE
sha256 show different results from sha256sum

### ISSUE THREAD

**Issue by oxitech239** [vibornoff/asmcrypto.js#99]
When calculating an empty string with `asmCrypto.SHA256.hex("");` the hash reads e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 this is as expteced since sha256sum returns e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 as well.

Whenever i enter text though. It immediately shows a different result. For example with asmcrypto A becomes 559aead08264d5795d3909718cdd05abd49572e84fe55590eef31a88a08fdffd while with sha256sum A becomes 06f961b802bc46ee168555f066d28f4f0e9afdf3f88174c1ee6f9de004fc30a0

I want to know if there's a way to have asmcrypto produce results in-line with sha256sum

Best Regards

**Comment by vibornoff** [comment]
How exactly do you supply a text to the `sha256sum`?
Suppose it's
```sh
$ echo "blah-blah" | sha256sum
```
Note that this way `echo` adds line ending to the text. To prevent it from adding `\n` you should specify `-n` flag. Try
```sh
echo -n "blah-blah" | sha256sum
```

**Comment by oxitech239** [comment]
Below are the results for sha256sum on the linux commandline using your method. It is indeed a PEBKAC issue.

echo "A" | sha256sum
06f961b802bc46ee168555f066d28f4f0e9afdf3f88174c1ee6f9de004fc30a0  -
echo -n "A" | sha256sum
559aead08264d5795d3909718cdd05abd49572e84fe55590eef31a88a08fdffd  -
